name: MCMiniGames
main: fr.mcminigames.benjaminloison.main.Main
version: 1.0.0
author: Benjamin Loison
description: Plugin
commands:
  game:
    description: Game manager
    aliases: [ge]

  group:
    description: Group manager
    aliases: [gp]

depends: [WorldEdit]
