name: AzzizCouscous
main: fr.azzizcouscous.benjaminloison.main.Main
version: 1.0.0
author: Benjamin Loison
description: Plugin for Azziz Couscous
commands:
  game:
    description: Game manager
    aliases: [ge]

  group:
    description: Group manager
    aliases: [gp]

depends: [WorldEdit]